### ISSUE TITLE
What level of Python ? 

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/app-insights-discovery#1]
Hello , I 'm trying to use the sample scripts with Python 3.5
I face several small issues (for example , I get the request to enclose print statements into parentheses) .
For which version of Python is the script written for: 2.7 or 3.5 ?

Thank you very much

**Comment by germanattanasio** [comment]
From what I saw in the code it will be python 2.7.
We should update the print statements to be compatible with Python 3.5... :man_shrugging:
